#!/bin/sh
#chkconfig: 345 60 40
   #description:epics1d
start(){
export V=`ps -ef|grep -v grep|grep "SCREEN -dmS DPU09IOC"`
if [ $V=="" ];then
echo -n $"Starting $prog:"
screen -dmS DPU09IOC
sleep 0.5
echo "DPU09 IOC"
screen -S  DPU09IOC -p 0 -X eval 'stuff "cd /usr/local/epics/virPV/iocBoot/iocvirPV \015"'
screen -S  DPU09IOC -p 0 -X eval 'stuff "./DPU09.cmd \015"'
echo "DPU09 EPICS IOC is Running";
else
return 0;
fi



}

stop(){
echo -n $"Shutting down $Prog:"
screen -S DPU09IOC -p 0 -X eval 'stuff "exit \015"'
screen -S DPU09IOC -p 0 -X eval 'stuff "exit \015"'
echo "EPICS IOC is Stoping"
return 0
}
restart() {
        stop
        start
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
restart)
        restart
        ;;
esac

